from torchvision import datasets, transforms
from base import BaseDataLoader

import random
from collections import Counter
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import Dataset

from base import BaseDataLoader
from data_loader import EcalDataIO
import h5py
import os

# ==== dataloaders ==== #

class MnistDataLoader(BaseDataLoader):
    """
    MNIST data loading demo using BaseDataLoader
    """
    def __init__(self, data_dir, batch_size, shuffle=True, validation_split=0.0, num_workers=1, training=True):
        trsfm = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])
        self.data_dir = data_dir
        self.dataset = datasets.MNIST(self.data_dir, train=training, download=True, transform=trsfm)
        super().__init__(self.dataset, batch_size, shuffle, validation_split, num_workers)

class data_loader(BaseDataLoader):
    """
    Generates a DL from the existing files - train.pt, test.pt generated by the functions in myutils.py
    """

    def __init__(self, data_dir, batch_size, shuffle=True, validation_split=0.0, num_workers=1, training=True):

        if training == True:
            self.dataset = torch.load(os.path.join('D:', os.sep, 'local_github', 'particles_nir_repo', 'data', 'train', 'train.pt'))
        else:
            self.dataset = torch.load(os.path.join('D:', os.sep, 'local_github', 'particles_nir_repo', 'data', 'test', 'test.pt'))

        print("Dataset len: ", len(self.dataset))
        super().__init__(self.dataset, batch_size, shuffle, validation_split, num_workers)


# ================== #

# ==== datasets ==== #

class Bin_energy_data(Dataset):
    """
    General dataset object -
    __getitem__: returns the d_tens (calorimeter matrix data), and the relevant info for the network to learn.
                 Either the num_showers for N training, or the mean energy for E training or final_list for 20bin train.
                 Also returns the num_showers and idx parameter for test purposes.
    """

    def __init__(self, en_dep_file, en_file, moment=1, min_shower_num=0, max_shower_num=10000, file=0):

        self.en_dep = EcalDataIO.ecalmatio(en_dep_file)  # Dict with 100000 samples {(Z,X,Y):energy_stamp}
        
        self.energies = EcalDataIO.energymatio(en_file)
        # self.energies = EcalDataIO.xymatio(en_file)

        self.moment = moment
        self.file = file

        # Eliminate multiple numbers of some kind
        min_shower_num = 0
        max_shower_num = 20
        if min_shower_num > 0:
            del_list = []
            for key in self.energies:
                if len(self.energies[key]) < min_shower_num or len(self.energies[key]) >= max_shower_num:
                    del_list.append(key)
            for d in del_list:
                del self.energies[d]
                del self.en_dep[d]

    def __len__(self):
        return len(self.en_dep)

    
    def __getitem__(self, idx):

        if torch.is_tensor(idx):
            idx = idx.tolist()
        key = list(self.en_dep.keys())[idx]

        d_tens = torch.zeros((110, 11, 21))  # Formatted as [x_idx, y_idx, z_idx]
        tmp = self.en_dep[key]

        for z, x, y in tmp:
            d_tens[x, y, z] = tmp[(z, x, y)]
        d_tens = d_tens.unsqueeze(0)  # Only in conv3d

        en_list = torch.Tensor(self.energies[key])
        num_showers = len(en_list)

        ######### Energy bins Generation ########
        hf = h5py.File(os.path.join('D:', os.sep, 'local_github', 'particles_nir_repo', 'num_classes.h5'), 'r')
        num_classes = hf.get('dataset_1')
        num_classes = int(np.array(num_classes))
        hf.close()

        x_lim = 13

        bin_num = num_classes
        final_list = [0] * bin_num  # The 20 here is the bin number - it may be changed of course.
        en_list.sort()
        final_list[:len(en_list)] = en_list
        final_list = torch.Tensor(final_list)  # Wrap it in a tensor - important for training and testing.
        #########################################

        return d_tens, final_list, num_showers, idx

